name: Check TODO Comments

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  find-todo-comments:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - uses: indigo-san/todo-comments-in-pr@main
      id: todos

    - name: Generate a summary of the tasks
      uses: actions/github-script@v7
      id: summary
      with:
        result-encoding: string
        script: |
          const tasks = JSON.parse('${{ steps.todos.outputs.tasks }}');
          let body = tasks.map(task => `https://github.com/${{ github.repository }}/blob/${{ github.sha }}/${item.fileName}#L${item.startLine}-L${item.endLine}`).join('\n');

          if (tasks.length > 0) {
            body = `The following TODO comments were found:\n\n${body}`;
          } else {
            body = 'No TODO comments were found.';
          }
          return body;

    - name: Comment on the pull request
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        header: todo-cooments
        recreate: true
        message: |
          ${{ steps.summary.outputs.result }}